### PR TITLE
pkg/linksharing/web: a simple reordering in the filesharing modal lay…

### PR DESCRIPTION
**Pull request by mbouzi**
…out.

## PR Checklist

- [x] The PR title is formatted as follows: `pkg/server: add TestXYZ for XYZ`
  - [x] The package name goes before the colon
  - [x] The part after the colon uses the verb tense + phrase that completes the blank in, "This change modifies Gateway-MT to ___________"
  - [x] Lowercase verb after the colon
  - [x] No trailing period
  - [x] Keep the title as short as possible. Ideally under 72 characters or shorter
  - [x] No Markdown

## Commit Message Body

- What, why, please describe the tests and the performance impact (if any)
- No Markdown
- The body is wrapped at 72 characters unless it's really needed (ASCII art, table, or long link)
- If there is a corresponding issue, add either `Closes #1234`, `Fixes #1234`, `Resolves #1234` or `Updates #1234` (the latter if this is not a complete fix) to this comment
- If referring to a repo other than `storj/gateway-mt`, you can use the `owner/repo#issue_number` syntax: `Fixes storj/common#1234`
- We do not use Signed-off-by lines. Please don't add them. Our Gerrit server & GitHub bots enforce CLA compliance instead
- More: https://github.com/storj/docs/blob/main/code/Git.md
- Delete these instructions once you have read and applied them

## Code Review Checklist (to be filled out by reviewer)

 - [x] Are there any authservice's database migrations? Are they forwards _and_ backwards compatible?
 - [x] Does the PR describe what changes are being made?
 - [x] Does the PR describe why the changes are being made?
 - [x] Does the code follow [our style guide](https://github.com/storj/docs/blob/main/code/Style.md)?
 - [x] Does the code follow [our testing guide](https://github.com/storj/docs/blob/main/code/Testing.md)?
 - [x] Is the PR appropriately sized? (If it could be broken into smaller PRs, it should be)
 - [x] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [x] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [x] Does any documentation needs updating?
 - [x] Do the database access patterns make sense?
 - [x] Copy the Commit Message Body section contents into the submit prompt upon PR completion

### CODE REVIEW

**Comment by halkyon** [comment]
Do you have a screenshot of what this is fixing? It seems good to me, but I'm not sure what the before and after looks like

**Review by amwolff — COMMENTED** [review]
The change looks good! Would you mind writing a short commit message body what changed and why? I know the change is simple, but it will be much easier for QA and us in the future to know how much this changed and how important it was/what the motivation was (if I understand correctly, this came from the discussion in #team-product (?)).

**Comment by mbouzi** [comment]
@amwolff Thanks for the heads up this makes sense! I'm not 100 percent sure why the change is being made, I just had this conversation for reference https://storj.slack.com/archives/C019JQJ4LTV/p1655902161447919?thread_ts=1655807036.483149&cid=C019JQJ4LTV

I'll go ahead and update the commit!

**Comment by halkyon** [comment]
Maybe the message could be something like "Re-ordering fix for improvements to mobile layout"? Unfortunately a link to a private Slack would not be that useful to anyone else looking in, from an open source point of view.

**Review by amwolff — APPROVED** [review]
@halkyon I will put the message you mentioned into the commit body while squashing & merging the commit.

**Review by halkyon — APPROVED** [review]

**Review by amwolff — APPROVED** [review]

**Pull request merged**
