### PR TITLE
pkg/linksharing/web: change height attribute in prefix-listing.html

### PR DESCRIPTION
**Pull request by pvdl**
Fixes HTML validation issue: Error: Bad value 40px for attribute height on element img: Expected a digit but saw p instead.

## PR Checklist

- [x] The PR title is formatted as follows: `pkg/server: add TestXYZ for XYZ`
  - [x] The package name goes before the colon
  - [x] The part after the colon uses the verb tense + phrase that completes the blank in, "This change modifies Gateway-MT to ___________"
  - [x] Lowercase verb after the colon
  - [x] No trailing period
  - [x] Keep the title as short as possible. Ideally under 72 characters or shorter
  - [x] No Markdown

## Commit Message Body

- What, why, please describe the tests and the performance impact (if any)
- No Markdown
- The body is wrapped at 72 characters unless it's really needed (ASCII art, table, or long link)
- If there is a corresponding issue, add either `Closes #1234`, `Fixes #1234`, `Resolves #1234` or `Updates #1234` (the latter if this is not a complete fix) to this comment
- If referring to a repo other than `storj/gateway-mt`, you can use the `owner/repo#issue_number` syntax: `Fixes storj/common#1234`
- We do not use Signed-off-by lines. Please don't add them. Our Gerrit server & GitHub bots enforce CLA compliance instead
- More: https://github.com/storj/docs/blob/main/code/Git.md
- Delete these instructions once you have read and applied them

## Code Review Checklist (to be filled out by reviewer)

 - [x] Are there any authservice's database migrations? Are they forwards _and_ backwards compatible?
 - [x] Does the PR describe what changes are being made?
 - [x] Does the PR describe why the changes are being made?
 - [x] Does the code follow [our style guide](https://github.com/storj/docs/blob/main/code/Style.md)?
 - [x] Does the code follow [our testing guide](https://github.com/storj/docs/blob/main/code/Testing.md)?
 - [x] Is the PR appropriately sized? (If it could be broken into smaller PRs, it should be)
 - [x] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [x] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [x] Does any documentation needs updating?
 - [x] Do the database access patterns make sense?
 - [x] Copy the Commit Message Body section contents into the submit prompt upon PR completion

### CODE REVIEW

**Review by amwolff — COMMENTED** [review]
Thanks for the fix. It looks good to me, but we'll need you to sign our CLA to merge this PR.

**Comment by pvdl** [comment]
> Thanks for the fix. It looks good to me, but we'll need you to sign our CLA to merge this PR.
Done

**Comment by stefanbenten** [comment]
@cla-bot check

**Comment by stefanbenten** [comment]
@cla-bot check

**Comment by cam-a** [comment]
nit pick: 
According to the PR checklist, the commit should be prefixed with the package: `pkg/linksharing`
Looks good otherwise

**Review by stefanbenten — APPROVED** [review]

**Review by amwolff — APPROVED** [review]

**Comment by stefanbenten** [comment]
Thank you for the contribution @pvdl !

**Pull request merged**
