### PR TITLE
auth/sqlauth: update lint ignore for staticcheck 2020.2

### PR DESCRIPTION
**Pull request by stefanbenten**
Fixes failing tests for: https://github.com/storj/ci/pull/24

### CODE REVIEW

**Review by zeebo — APPROVED** [review]
Oh, this is better than what I did.

**Review by kristaxox — APPROVED** [review]

**Review by VinozzZ — APPROVED** [review]

**Comment by dominikh** [comment]
@stefanbenten Do you want to fill me in on what triggered this change?

**Comment by egonelbre** [comment]
@dominikh hey, it was using this ignore before:

```
//lint:file-ignore * generated file
```

e.g. https://github.com/storj/storj/commit/9fe477899b373a9d3faea611e41cefb4d05bbd54

But, I think the change from two-line ignore to single-line was a script cleanup.

**Comment by dominikh** [comment]
Ah, hm. The "Files changed" view looks entirely different from the 3 individual commits. Interesting.

**Pull request merged**
